$(document).ready(function(){
    $("#one").click(function(){
        console.log("1");
        $("#f").load("./1.html");
    });
    $("#two").click(function(){
        console.log("2");
        $("#f").load("./2.html");
    });
});